#!/usr/bin/env python

import re
import os
import glob

listdir = os.listdir()

regex = re.compile("day*")

srcdirs = [x for x in listdir if regex.match(x)]
for srcdir in srcdirs:
    os.chdir(srcdir)
    listfiles = os.listdir()
    cfiles = glob.glob("*.c")
    for cfile in cfiles:
        output = cfile.split(".")[0]
        print(f"compiling {cfile} in {srcdir} to ./build/{output}")
        os.system(f"gcc {cfile} -o ../build/{output} -lm")
    os.chdir("..")